-- Usage metering and billing events
-- Idempotent creation for safe re-runs

-- Usage events: track metered actions per tenant
CREATE TABLE IF NOT EXISTS public.usage_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  resource TEXT NOT NULL CHECK (resource IN ('booking','message')),
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_usage_events_tenant_time
  ON public.usage_events (tenant_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_usage_events_resource_time
  ON public.usage_events (resource, occurred_at DESC);

-- Daily aggregates (optional materialized table, can be generated by jobs)
CREATE TABLE IF NOT EXISTS public.usage_daily_totals (
  tenant_id UUID NOT NULL,
  resource TEXT NOT NULL CHECK (resource IN ('booking','message')),
  date DATE NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (tenant_id, resource, date)
);

-- Billing events: record Stripe invoice/charge/subscription webhooks
CREATE TABLE IF NOT EXISTS public.billing_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID,
  provider TEXT NOT NULL DEFAULT 'stripe',
  event_type TEXT NOT NULL,
  event_id TEXT,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_billing_events_type_time
  ON public.billing_events (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_billing_events_tenant_time
  ON public.billing_events (tenant_id, created_at DESC);


